# Generated by Django 3.2.4 on 2021-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='covers/'),
        ),
    ]
