# Generated by Django 3.2.4 on 2021-06-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('book_detail_accesss', 'can view book details page')]},
        ),
    ]
