# Generated by Django 3.2.4 on 2021-06-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('book_detail_accesss', 'can view book details page')]},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
    ]
